//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tnda_fix.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tndaEntities : DbContext
    {
        public tndaEntities()
            : base("name=tndaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACC> ACCs { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Family> Families { get; set; }
        public virtual DbSet<FamilyInfo> FamilyInfoes { get; set; }
        public virtual DbSet<FamilyLinkInfo> FamilyLinkInfoes { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonLog> PersonLogs { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
    }
}
