//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tnda_fix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyLinkInfo
    {
        public int id { get; set; }
        public Nullable<int> id_family { get; set; }
        public Nullable<int> id_info { get; set; }
    
        public virtual Family Family { get; set; }
        public virtual FamilyInfo FamilyInfo { get; set; }
    }
}
