//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tnda_fix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonLog
    {
        public int ID { get; set; }
        public int ID_Per { get; set; }
        public string CollumName { get; set; }
        public string OldData { get; set; }
        public string NewData { get; set; }
        public int ID_Ad { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ACC ACC { get; set; }
        public virtual Person Person { get; set; }
    }
}
